# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/collections_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 838)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.back_to_home_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_to_home_btn.setMinimumSize(QtCore.QSize(40, 30))
        self.back_to_home_btn.setMaximumSize(QtCore.QSize(40, 30))
        self.back_to_home_btn.setStyleSheet("")
        self.back_to_home_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-back-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_to_home_btn.setIcon(icon)
        self.back_to_home_btn.setIconSize(QtCore.QSize(25, 25))
        self.back_to_home_btn.setFlat(True)
        self.back_to_home_btn.setObjectName("back_to_home_btn")
        self.gridLayout.addWidget(self.back_to_home_btn, 0, 0, 1, 1)
        self.search_lin = QtWidgets.QLineEdit(self.centralwidget)
        self.search_lin.setMinimumSize(QtCore.QSize(750, 40))
        self.search_lin.setMaximumSize(QtCore.QSize(750, 40))
        self.search_lin.setStyleSheet("border-radius:10% 10%;\n"
"padding:10px;\n"
"font-size:16px")
        self.search_lin.setClearButtonEnabled(True)
        self.search_lin.setObjectName("search_lin")
        self.gridLayout.addWidget(self.search_lin, 0, 1, 1, 1)
        self.add_collection_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_collection_btn.setMinimumSize(QtCore.QSize(40, 30))
        self.add_collection_btn.setMaximumSize(QtCore.QSize(40, 30))
        self.add_collection_btn.setStyleSheet("")
        self.add_collection_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-add-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_collection_btn.setIcon(icon1)
        self.add_collection_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_collection_btn.setFlat(True)
        self.add_collection_btn.setObjectName("add_collection_btn")
        self.gridLayout.addWidget(self.add_collection_btn, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(790, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(790, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 788, 772))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.collection_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.collection_groupbox.setGeometry(QtCore.QRect(10, 10, 771, 81))
        self.collection_groupbox.setTitle("")
        self.collection_groupbox.setObjectName("collection_groupbox")
        self.collection_icon_lbl = QtWidgets.QPushButton(self.collection_groupbox)
        self.collection_icon_lbl.setEnabled(True)
        self.collection_icon_lbl.setGeometry(QtCore.QRect(10, 10, 71, 61))
        self.collection_icon_lbl.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.collection_icon_lbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.collection_icon_lbl.setStyleSheet("background-color: rgb(222, 221, 218,0);\n"
"border-radius: 4% 4%;\n"
"padding:10px;\n"
"font-size:20px")
        self.collection_icon_lbl.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-abc-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.collection_icon_lbl.setIcon(icon2)
        self.collection_icon_lbl.setIconSize(QtCore.QSize(40, 40))
        self.collection_icon_lbl.setAutoRepeat(False)
        self.collection_icon_lbl.setAutoExclusive(False)
        self.collection_icon_lbl.setFlat(True)
        self.collection_icon_lbl.setObjectName("collection_icon_lbl")
        self.collection_name_lbl = QtWidgets.QLabel(self.collection_groupbox)
        self.collection_name_lbl.setGeometry(QtCore.QRect(80, 10, 681, 61))
        self.collection_name_lbl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.collection_name_lbl.setStyleSheet("\n"
"border-radius: 4% 4%;\n"
"padding:20px;\n"
"font-size:22px;\n"
"background-color: rgb(222, 221, 218);")
        self.collection_name_lbl.setObjectName("collection_name_lbl")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 1, 2, 2)
        spacerItem1 = QtWidgets.QSpacerItem(91, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.collection_name_lbl.setText(_translate("MainWindow", "Main"))
import icons_rc
